<?php

namespace Database\Seeders;

use App\Models\Content;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $contents = [
            // ========================================
            // NAVIGATION (components/navigation.blade.php)
            // ========================================
            [
                'key' => 'nav_logo',
                'type' => 'image',
                'value' => 'images/logo.png',
                'category' => 'Composant',
                'page' => 'Navigation',
                'section' => 'Header',
                'label' => 'Logo de navigation',
                'description' => 'Logo principal affiché dans la barre de navigation'
            ],
            [
                'key' => 'nav_links',
                'type' => 'text',
                'value' => json_encode(['Accueil', 'Qui sommes-nous', 'Nos services', 'Services dédiés', 'Localisation', 'Annuaire']),
                'category' => 'Composant',
                'page' => 'Navigation',
                'section' => 'Menu',
                'label' => 'Liens de navigation',
                'description' => 'Liste des liens du menu de navigation principal'
            ],
            [
                'key' => 'nav_contact_button',
                'type' => 'text',
                'value' => 'Contactez-nous',
                'category' => 'Composant',
                'page' => 'Navigation',
                'section' => 'Menu',
                'label' => 'Bouton de contact',
                'description' => 'Texte du bouton de contact dans la navigation'
            ],

            // ========================================
            // FOOTER (components/footer.blade.php)
            // ========================================
            [
                'key' => 'footer_company_title',
                'type' => 'text',
                'value' => 'Noha Transports',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Informations entreprise',
                'label' => 'Nom de l\'entreprise',
                'description' => 'Nom de l\'entreprise dans le footer'
            ],
            [
                'key' => 'footer_company_description',
                'type' => 'text',
                'value' => 'Le service qui facilite votre quotidien',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Informations entreprise',
                'label' => 'Description de l\'entreprise',
                'description' => 'Slogan de l\'entreprise dans le footer'
            ],
            [
                'key' => 'footer_social_title',
                'type' => 'text',
                'value' => 'Suivez-nous',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Réseaux sociaux',
                'label' => 'Titre Réseaux sociaux',
                'description' => 'Titre de la section réseaux sociaux'
            ],
            [
                'key' => 'footer_social1_url',
                'type' => 'text',
                'value' => '#',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Réseaux sociaux',
                'label' => 'Réseau social 1',
                'description' => 'URL du premier réseau social'
            ],
            [
                'key' => 'footer_social2_url',
                'type' => 'text',
                'value' => '#',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Réseaux sociaux',
                'label' => 'Réseau social 2',
                'description' => 'URL du deuxième réseau social'
            ],
            [
                'key' => 'footer_social3_url',
                'type' => 'text',
                'value' => '#',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Réseaux sociaux',
                'label' => 'Réseau social 3',
                'description' => 'URL du troisième réseau social'
            ],
            [
                'key' => 'footer_contact_title',
                'type' => 'text',
                'value' => 'Contact',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Informations de contact',
                'label' => 'Titre Contact',
                'description' => 'Titre de la section contact'
            ],
            [
                'key' => 'footer_phone',
                'type' => 'text',
                'value' => '0696 16 12 77',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Contact',
                'label' => 'Téléphone',
                'description' => 'Numéro de téléphone de contact'
            ],
            [
                'key' => 'footer_email',
                'type' => 'text',
                'value' => 'noha.transports@hotmail.com',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Contact',
                'label' => 'Email',
                'description' => 'Adresse email de contact'
            ],
            [
                'key' => 'footer_address',
                'type' => 'text',
                'value' => "12 Rue des Arts et Métiers\nImmeubles Équinoxes\n97200 Fort-de-France",
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Contact',
                'label' => 'Adresse',
                'description' => 'Adresse postale de l\'entreprise'
            ],
            [
                'key' => 'footer_legal_title',
                'type' => 'text',
                'value' => 'Pages légales',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Pages légales',
                'label' => 'Titre Pages légales',
                'description' => 'Titre de la section pages légales'
            ],
            [
                'key' => 'footer_copyright',
                'type' => 'text',
                'value' => 'Noha Transports © 2025, Tous droits réservés.',
                'category' => 'Composant',
                'page' => 'Footer',
                'section' => 'Copyright',
                'label' => 'Copyright',
                'description' => 'Mention de copyright'
            ],

            // ========================================
            // PAGE ACCUEIL (accueil.blade.php)
            // ========================================
            // Section Hero
            [
                'key' => 'accueil_hero_title',
                'type' => 'text',
                'value' => 'Noha Transports',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Hero',
                'label' => 'Titre principal',
                'description' => 'Titre principal de la section hero'
            ],
            [
                'key' => 'accueil_hero_subtitle',
                'type' => 'text',
                'value' => 'Votre solution logistique !',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Hero',
                'label' => 'Pharse d\'accroche',
                'description' => 'Phrase d\'accroche de la section hero'
            ],
            [
                'key' => 'accueil_hero_bg_image',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Hero',
                'label' => 'Image de fond',
                'description' => 'Image de fond de la section hero'
            ],

            // Section Qui sommes-nous
            [
                'key' => 'accueil_about_title',
                'type' => 'text',
                'value' => 'Qui sommes-nous ?',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Qui sommes-nous',
                'label' => 'Titre Qui sommes_nous',
                'description' => 'Titre de la section Qui sommes-nous'
            ],
            [
                'key' => 'accueil_about_description',
                'type' => 'text',
                'value' => "Nous imaginons un avenir dans lequel il y a une prise en charge approfondie et durable de la personne en perte d\'autonomie.\n\nNoha Transports est une société française qui intègre pleinement le handicap dans ses infrastructures, et également dans le domaine de l\'emploi.",
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Qui sommes-nous',
                'label' => 'Description Qui sommes_nou',
                'description' => 'Texte de présentation de l\'entreprise'
            ],
            [
                'key' => 'accueil_about_image',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2065&q=80',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Qui sommes-nous',
                'label' => 'Image Qui sommes_nou',
                'description' => 'Image illustrative de la section Qui sommes-nous'
            ],

            // Section Services
            [
                'key' => 'accueil_services_title',
                'type' => 'text',
                'value' => 'Nos services',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Nos services',
                'label' => 'Titre Nos services',
                'description' => 'Titre de la section Nos services'
            ],
            [
                'key' => 'accueil_service1_title',
                'type' => 'text',
                'value' => 'Transports de médicaments à domicile',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Nos services',
                'label' => 'Service 1 - Titre',
                'description' => 'Titre du premier service'
            ],
            [
                'key' => 'accueil_service1_description',
                'type' => 'text',
                'value' => 'Faites-nous parvenir votre ordonnance, nous nous occupons de l\'acheminement sous 24h.',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Nos services',
                'label' => 'Service 1 - Description',
                'description' => 'Description du premier service'
            ],
            [
                'key' => 'accueil_service2_title',
                'type' => 'text',
                'value' => 'Gestion de prise de commande en ligne',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Nos services',
                'label' => 'Service 2 - Titre',
                'description' => 'Titre du deuxième service'
            ],
            [
                'key' => 'accueil_service2_description',
                'type' => 'text',
                'value' => 'Une prise commande rapide et efficace pour faciliter votre quotidien.',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Nos services',
                'label' => 'Service 2 - Description',
                'description' => 'Description du deuxième service'
            ],
            [
                'key' => 'accueil_services_image',
                'type' => 'image',
                'value' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2069&q=80',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Nos services',
                'label' => 'Image',
                'description' => 'Image illustrative de la section services'
            ],

            // Section Services Santé Hero
            [
                'key' => 'accueil_services_sante_title',
                'type' => 'text',
                'value' => 'Services pour les professionnels de santé',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Services dédiés',
                'label' => 'Titre Services dédiés',
                'description' => 'Titre de la section services santé'
            ],
            [
                'key' => 'accueil_services_sante_description',
                'type' => 'text',
                'value' => 'Besoin de livrer des équipements ou des médicaments en urgence ? Noha Transports est votre partenaire logistique de confiance. Nous garantissons une prise en charge immédiate et un acheminement rapide pour que vous puissiez vous concentrer sur ce qui compte le plus : vos patients.',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Services dédiés',
                'label' => 'Description Services dédiés',
                'description' => 'Description des services pour professionnels de santé'
            ],

            [
                'key' => 'accueil_services_sante_button',
                'type' => 'text',
                'value' => 'Découvrez nos services',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Services dédiés',
                'label' => 'Bouton Services dédiés',
                'description' => 'Texte du bouton d\'action'
            ],


            // Section Où nous trouver
            [
                'key' => 'accueil_localisation_iframe',
                'type' => 'text',
                'value' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1930.449417576726!2d-61.044326021596355!3d14.60483839750429!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c6aa15d37fd051d%3A0x5fead3840118fcbe!2sBeBOOSTER!5e0!3m2!1sfr!2sfr!4v1758206451231!5m2!1sfr!2sfr" class="w-full h-full border-0" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
                'category' => 'Page',
                'page' => 'Accueil',
                'section' => 'Localisation',
                'label' => 'Carte Google Maps',
                'description' => 'Code iframe de la carte Google Maps'
            ],

            // ========================================
            // PAGE SERVICES (pages/services.blade.php)
            // ========================================
            // Section Hero
            [
                'key' => 'services_hero_title',
                'type' => 'text',
                'value' => 'Un service de transport fiable et sécurisé pour les professionnels de santé',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Hero',
                'label' => 'Titre principal',
                'description' => 'Titre principal de la section hero de la page Services',
            ],
            [
                'key' => 'services_hero_description',
                'type' => 'text',
                'value' => 'Nous comprenons que le transport de médicaments et de produits de santé requiert une attention et une expertise particulières. C\'est pourquoi nous avons développé un service logistique dédié, conçu spécifiquement pour les pharmacies et les professionnels de santé, garantissant la sécurité, la traçabilité et la rapidité de chaque livraison.',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Hero',
                'label' => 'Description',
                'description' => 'Description détaillée de la section hero',
            ],

            // Section Engagements
            [
                'key' => 'services_engagements_title',
                'type' => 'text',
                'value' => 'Nos engagements',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Titre section Nos engagements',
                'description' => 'Titre de la section Nos engagements',
            ],
            // Card 1
            [
                'key' => 'services_engagement1_title',
                'type' => 'text',
                'value' => 'Acheminement rapide et sécurisé',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Engagement 1 - Titre',
                'description' => 'Titre du premier engagement',
            ],
            [
                'key' => 'services_engagement1_description',
                'type' => 'text',
                'value' => "Livraison sous 24h pour les commandes passées par les pharmacies.\n\nRespect de la chaîne du froid (si applicable, pensez à vérifier ce point avec votre client).\n\nVéhicules et emballages adaptés pour préserver l\'intégrité des produits.",
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Engagement 1 - Description',
                'description' => 'Description détaillée du premier engagement',
            ],
            // Card 2
            [
                'key' => 'services_engagement2_title',
                'type' => 'text',
                'value' => 'Traçabilité complète et en temps réel',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Engagement 2 - Titre',
                'description' => 'Titre du deuxième engagement',
            ],
            [
                'key' => 'services_engagement2_description',
                'type' => 'text',
                'value' => "Système de suivi en ligne permettant aux pharmaciens de connaître la localisation exacte de leurs livraisons.\n\nNotifications de statut de livraison (en préparation, en cours de livraison, livrée).\n\nPreuve de livraison avec signature électronique",
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Engagement 2 - Description',
                'description' => 'Description détaillée du deuxième engagement',
            ],
            // Card 3
            [
                'key' => 'services_engagement3_title',
                'type' => 'text',
                'value' => 'Respect de la confidentialité et des normes sanitaires',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Engagement 3 - Titre',
                'description' => 'Titre du troisième engagement',
            ],
            [
                'key' => 'services_engagement3_description',
                'type' => 'text',
                'value' => "Formation du personnel aux bonnes pratiques de distribution (BPD) pour les produits de santé.\n\nRespect strict de la confidentialité des données et des informations médicales.\n\nProtocole de désinfection et d\'hygiène rigoureux pour les véhicules et les livreurs.",
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Nos engagements',
                'label' => 'Engagement 3 - Description',
                'description' => 'Description détaillée du troisième engagement',
            ],

            // Section Fonctionnement
            [
                'key' => 'services_fonctionnement_title',
                'type' => 'text',
                'value' => 'Comment ça marche ?',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Titre section Comment ça marche',
                'description' => 'Titre de la section Comment ça marche',
            ],
            // Card 1
            [
                'key' => 'services_etape1_title',
                'type' => 'text',
                'value' => 'Passage de la commande',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Étape 1 - Titre',
                'description' => 'Titre de la première étape',
            ],
            [
                'key' => 'services_etape1_description',
                'type' => 'text',
                'value' => 'Nous saisissons votre commande et vos informations de livraison.',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Étape 1 - Description',
                'description' => 'Description de la première étape',
            ],
            // Card 2
            [
                'key' => 'services_etape2_title',
                'type' => 'text',
                'value' => 'Préparation et prise en charge',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Étape 2 - Titre',
                'description' => 'Titre de la deuxième étape',
            ],
            [
                'key' => 'services_etape2_description',
                'type' => 'text',
                'value' => 'Nous préparons et prenons en charge les médicaments à la pharmacie.',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Étape 2 - Description',
                'description' => 'Description de la deuxième étape',
            ],
            // Card 3
            [
                'key' => 'services_etape3_title',
                'type' => 'text',
                'value' => 'Livraison',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Étape 3 - Titre',
                'description' => 'Titre de la troisième étape',
            ],
            [
                'key' => 'services_etape3_description',
                'type' => 'text',
                'value' => 'Le livreur remet la commande au domicile du patient.',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Comment ça marche',
                'label' => 'Étape 3 - Description',
                'description' => 'Description de la troisième étape',
            ],

            // Section Engagement Social
            [
                'key' => 'services_social_title',
                'type' => 'text',
                'value' => 'Notre engagement social',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Notre engagement social',
                'label' => 'Titre section Notre engagement social',
                'description' => 'Titre de la section Notre engagement social',
            ],
            [
                'key' => 'services_social1_title',
                'type' => 'text',
                'value' => 'Soutien aux patients dépendants',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Notre engagement social',
                'label' => 'Engagement social 1 - Titre',
                'description' => 'Titre du premier engagement social',
            ],
            // Card 1
            [
                'key' => 'services_social1_description',
                'type' => 'text',
                'value' => 'Nous mettons en avant l\'aide apportée aux personnes en perte d\'autonomie ou en situation de handicap, en leur facilitant l\'accès aux médicaments essentiels sans qu\'ils aient à se déplacer.',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Notre engagement social',
                'label' => 'Engagement social 1 - Description',
                'description' => 'Description du premier engagement social',
            ],
            [
                'key' => 'services_social2_title',
                'type' => 'text',
                'value' => 'Soutien à l\'intégration professionnelle',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Notre engagement social',
                'label' => 'Engagement social 2 - Titre',
                'description' => 'Titre du deuxième engagement social',
            ],
            // Card 2
            [
                'key' => 'services_social2_description',
                'type' => 'text',
                'value' => 'Notre société est engagée dans l\'intégration du handicap dans le domaine de l\'emploi, ce qui renforce l\'image de marque de votre client.',
                'category' => 'Page',
                'page' => 'Services',
                'section' => 'Notre engagement social',
                'label' => 'Engagement social 2 - Description',
                'description' => 'Description du deuxième engagement social',
            ],

            // ========================================
            // PAGE ANNUAIRE (pages/annuaire.blade.php)
            // ========================================
            [
                'key' => 'annuaire_hero_title',
                'type' => 'text',
                'value' => 'Annuaire des pharmacies',
                'category' => 'Page',
                'page' => 'Annuaire',
                'section' => 'Hero',
                'label' => 'Titre principal',
                'description' => 'Titre principal de la page Annuaire',
            ],
            
            // ========================================
            // MENTIONS LÉGALES (legal/mentions.blade.php)
            // ========================================
            // Section Hero
            [
                'key' => 'mentions_hero_title',
                'type' => 'text',
                'value' => 'Mentions légales',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Hero',
                'label' => 'Titre principal',
                'description' => 'Titre principal de la page Mentions légales',
            ],
            [
                'key' => 'mentions_editeur_title',
                'type' => 'text',
                'value' => '1. Éditeur du site',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Titre section Éditeur',
                'description' => 'Titre de la section Éditeur du site',
            ],
            // Section Éditeur
            [
                'key' => 'mentions_editeur_raison_sociale',
                'type' => 'text',
                'value' => 'Noha Transports',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Raison sociale',
                'description' => 'Raison sociale de l\'entreprise',
            ],
            [
                'key' => 'mentions_editeur_capital',
                'type' => 'text',
                'value' => '[Montant en €]',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Capital social',
                'description' => 'Montant du capital social de l\'entreprise',
            ],
            [
                'key' => 'mentions_editeur_siege_social',
                'type' => 'text',
                'value' => '12 Rue des Arts et Métiers Immeubles Équinoxes 97200 Fort-de-France',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Siège social',
                'description' => 'Adresse du siège social de l\'entreprise',
            ],
            [
                'key' => 'mentions_editeur_siret',
                'type' => 'text',
                'value' => '[Numéro SIRET]',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Numéro SIRET',
                'description' => 'Numéro SIRET de l\'entreprise',
            ],
            [
                'key' => 'mentions_editeur_rcs',
                'type' => 'text',
                'value' => '[Ville + numéro RCS]',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'RCS',
                'description' => 'Numéro RCS de l\'entreprise',
            ],
            [
                'key' => 'mentions_editeur_email',
                'type' => 'text',
                'value' => 'noha.transports@hotmail.com',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Email',
                'description' => 'Adresse email de contact de l\'entreprise',
            ],
            [
                'key' => 'mentions_editeur_telephone',
                'type' => 'text',
                'value' => '0696 16 12 77',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Éditeur',
                'label' => 'Téléphone',
                'description' => 'Numéro de téléphone de l\'entreprise',
            ],
            // Section Activité et Mission
            [
                'key' => 'mentions_activite_title',
                'type' => 'text',
                'value' => '2. Activité et Mission',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Activité',
                'label' => 'Titre section Activité',
                'description' => 'Titre de la section Activité et Mission',
            ],
            [
                'key' => 'mentions_activite_description',
                'type' => 'text',
                'value' => "Noha Transports est spécialisée dans le transport et la logistique de médicaments. Nous agissons comme intermédiaire essentiel pour faciliter la prise en charge d'ordonnances et la livraison de médicaments à domicile pour les citoyens, les aidants et les professionnels de santé.",
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Activité',
                'label' => 'Description activité',
                'description' => 'Description de l\'activité de l\'entreprise',
            ],
            [
                'key' => 'mentions_activite_services_subtitle',
                'type' => 'text',
                'value' => 'Nos services clés :',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Activité',
                'label' => 'Sous-titre services',
                'description' => 'Sous-titre de la liste des services clés',
            ],
            [
                'key' => 'mentions_activite_services_list',
                'type' => 'text',
                'value' => json_encode([
                    'Acheminement rapide des colis sous 24h.',
                    'Gestion simplifiée des prises de commande en ligne.',
                ]),
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Activité',
                'label' => 'Liste des services',
                'description' => 'Liste des services clés (format JSON)',
            ],
            // Section RGPD
            [
                'key' => 'mentions_rgpd_title',
                'type' => 'text',
                'value' => '3. Protection des Données Personnelles (RGPD)',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'RGPD',
                'label' => 'Titre section RGPD',
                'description' => 'Titre de la section Protection des données',
            ],
            [
                'key' => 'mentions_rgpd_description',
                'type' => 'text',
                'value' => 'Conformément au RGPD, vos données sont collectées uniquement pour le traitement des commandes et des demandes de contact. Elles ne sont pas partagées à des fins commerciales sans votre consentement.',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'RGPD',
                'label' => 'Description RGPD',
                'description' => 'Description de la politique RGPD',
            ],
            [
                'key' => 'mentions_rgpd_droits_subtitle',
                'type' => 'text',
                'value' => 'Vos droits (Accès, Rectification, Suppression) :', 
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'RGPD',
                'label' => 'Sous-titre droits',
                'description' => 'Sous-titre de la section droits RGPD',
            ],
            [
                'key' => 'mentions_rgpd_email',
                'type' => 'text', 
                'value' => 'noha.transports@hotmail.com', 
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'RGPD',
                'label' => 'Email RGPD',
                'description' => 'Email pour les demandes RGPD',
            ],
            [
                'key' => 'mentions_rgpd_adresse',
                'type' => 'text',
                'value' => '12 Rue des Arts et Métiers, Immeubles Équinoxes, 97200 Fort-de-France', 
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'RGPD',
                'label' => 'Adresse RGPD',
                'description' => 'Adresse pour les demandes RGPD',
            ],
            // Section Propriété Intellectuelle
            [
                'key' => 'mentions_propriete_title',
                'type' => 'text',
                'value' => '4. Propriété Intellectuelle',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Propriété intellectuelle',
                'label' => 'Titre section Propriété',
                'description' => 'Titre de la section Propriété intellectuelle',
            ],
            [
                'key' => 'mentions_propriete_description',
                'type' => 'text',
                'value' => 'Tous les éléments du site (textes, images, logos, etc.) sont la propriété exclusive de Noha Transports. Toute reproduction ou utilisation non autorisée est strictement interdite.',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Propriété intellectuelle',
                'label' => 'Description Propriété',
                'description' => 'Description des droits de propriété intellectuelle',
            ],
            [
                'key' => 'mentions_hebergeur_title',
                'type' => 'text',
                'value' => '5. Hébergeur',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Hébergeur',
                'label' => 'Titre section Hébergeur',
                'description' => 'Titre principal de la section Hébergeur',
            ],
            [
                'key' => 'mentions_hebergeur_nom',
                'type' => 'text',
                'value' => '[Nom de l’hébergeur]',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Hébergeur',
                'label' => 'Nom de l’hébergeur',
                'description' => 'Nom complet de la société d’hébergement',
            ],
            [
                'key' => 'mentions_hebergeur_adresse',
                'type' => 'text',
                'value' => '[Adresse complète de l’hébergeur]',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Hébergeur',
                'label' => 'Adresse de l’hébergeur',
                'description' => 'Adresse postale complète de la société d’hébergement',
            ],
            [
                'key' => 'mentions_hebergeur_contact',
                'type' => 'text',
                'value' => '[Numéro de l’hébergeur]',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Hébergeur',
                'label' => 'Contact de l’hébergeur',
                'description' => 'Numéro de téléphone ou email de contact de l’hébergeur',
            ],

            // Section Responsabilité et Droit Applicable
            [
                'key' => 'mentions_responsabilite_title',
                'type' => 'text',
                'value' => '6. Responsabilité & Droit Applicable',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Responsabilité',
                'label' => 'Titre section Responsabilité',
                'description' => 'Titre principal de la section Responsabilité et droit applicable',
            ],
            [
                'key' => 'mentions_responsabilite_limitation_title',
                'type' => 'text',
                'value' => 'Limitation de Responsabilité',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Responsabilité',
                'label' => 'Sous-titre Limitation de responsabilité',
                'description' => 'Sous-titre pour la limitation de responsabilité',
            ],
            [
                'key' => 'mentions_responsabilite_limitation_text',
                'type' => 'text',
                'value' => "Noha Transports ne peut être tenu responsable des erreurs, omissions ou dysfonctionnements techniques indépendants de sa volonté, bien que nous assurions la plus grande rigueur dans la mise à jour des informations.",
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Responsabilité',
                'label' => 'Texte limitation de responsabilité',
                'description' => 'Texte décrivant les limites de responsabilité de Noha Transports',
            ],
            [
                'key' => 'mentions_responsabilite_droit_title',
                'type' => 'text',
                'value' => 'Droit Applicable',
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Responsabilité',
                'label' => 'Sous-titre Droit applicable',
                'description' => 'Sous-titre précisant le droit applicable aux mentions légales',
            ],
            [
                'key' => 'mentions_responsabilite_droit_text',
                'type' => 'text',
                'value' => "Les présentes mentions légales sont régies par le droit français. Tout litige non résolu à l'amiable sera soumis aux tribunaux français compétents.",
                'category' => 'Page',
                'page' => 'Mentions légales',
                'section' => 'Responsabilité',
                'label' => 'Texte droit applicable',
                'description' => 'Texte définissant la juridiction applicable en cas de litige',
            ],
            // ========================================
            // POLITIQUE DE CONFIDENTIALITÉ (legal/privacy.blade.php)
            // ========================================
            [
                'key' => 'privacy_hero_title',
                'type' => 'text',
                'value' => 'Politique de confidentialité',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Hero',
                'label' => 'Titre principal',
                'description' => 'Titre principal de la page Politique de confidentialité',
            ],

            // Section Introduction
            [
                'key' => 'privacy_intro_title',
                'type' => 'text',
                'value' => '1. Introduction',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Hero',
                'label' => 'Titre introduction',
                'description' => 'Titre de la section introduction de la politique de confidentialité',
            ],
            [
                'key' => 'privacy_intro_description',
                'type' => 'text',
                'value' => "La présente politique de confidentialité a pour objectif d’informer les utilisateurs de nos services sur la manière dont Noha Transports collecte, utilise, conserve et protège les données personnelles. En utilisant notre site internet et nos services, vous acceptez la présente politique.",
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Hero',
                'label' => 'Texte introduction',
                'description' => 'Description d’introduction à la politique de confidentialité',
            ],

            // Section Responsable du traitement
            [
                'key' => 'privacy_responsable_title',
                'type' => 'text',
                'value' => '2. Responsable du traitement',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Titre responsable',
                'description' => 'Titre de la section sur le responsable du traitement',
            ],
            [
                'key' => 'privacy_responsable_societe',
                'type' => 'text',
                'value' => 'Noha Transports',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Société responsable',
                'description' => 'Nom de la société responsable du traitement des données',
            ],
            [
                'key' => 'privacy_responsable_activite',
                'type' => 'text',
                'value' => "Intermédiaire entre les professionnels de santé et les citoyens pour la gestion d’ordonnances et la livraison de médicaments à domicile.",
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Activité responsable',
                'description' => 'Description de l’activité du responsable du traitement',
            ],
            [
                'key' => 'privacy_responsable_email',
                'type' => 'text',
                'value' => 'noha.transports@hotmail.com',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Email responsable',
                'description' => 'Adresse email du responsable du traitement',
            ],
            [
                'key' => 'privacy_responsable_adresse',
                'type' => 'text',
                'value' => '12 Rue des Arts et Métiers, Immeubles Équinoxes, 97200 Fort-de-France',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Adresse responsable',
                'description' => 'Adresse postale du responsable du traitement des données',
            ],

            // Section Données collectées
            [
                'key' => 'privacy_donnees_title',
                'type' => 'text',
                'value' => '3. Données collectées',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Titre données collectées',
                'description' => 'Titre de la section sur les types de données collectées',
            ],
            [
                'key' => 'privacy_donnees_list',
                'type' => 'text',
                'value' => json_encode([
                    'Données d’identification : nom, prénom, adresse, téléphone, e-mail.',
                    'Données de santé : informations liées aux ordonnances (strict respect du secret professionnel).',
                    'Données de navigation : cookies, adresse IP, données techniques liées à l’utilisation du site.',
                ]),
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Collecte des données',
                'label' => 'Liste des données collectées',
                'description' => 'Liste des types de données collectées par le site',
            ],

            // Section Finalités du traitement
            [
                'key' => 'privacy_finalites_title',
                'type' => 'text',
                'value' => '4. Finalités du traitement',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Utilisation des données',
                'label' => 'Titre finalités du traitement',
                'description' => 'Titre de la section expliquant les finalités du traitement des données',
            ],
            [
                'key' => 'privacy_finalites_list',
                'type' => 'text',
                'value' => json_encode([
                    'Assurer la prise en charge des commandes et livraisons de médicaments à domicile.',
                    'Gérer la relation entre les pharmacies, les aidants et les citoyens.',
                    'Répondre aux demandes via le formulaire de contact.',
                    'Améliorer nos services et assurer le suivi logistique.',
                    'Respecter nos obligations légales et réglementaires.',
                ]),
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Utilisation des données',
                'label' => 'Liste des finalités',
                'description' => 'Liste des objectifs pour lesquels les données sont utilisées',
            ],

            // Section Base légale du traitement
            [
                'key' => 'privacy_base_legale_title',
                'type' => 'text',
                'value' => '5. Base légale du traitement',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Utilisation des données',
                'label' => 'Titre base légale',
                'description' => 'Titre de la section précisant la base légale du traitement',
            ],
            [
                'key' => 'privacy_base_legale_list',
                'type' => 'text',
                'value' => json_encode([
                    'Exécution d’un contrat (prise en charge et livraison).',
                    'Consentement (pour la collecte via cookies et formulaires).',
                    'Obligations légales en matière de santé et de transport.',
                ]),
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Utilisation des données',
                'label' => 'Liste base légale',
                'description' => 'Liste des fondements juridiques du traitement des données',
            ],

            // Section Durée de conservation
            [
                'key' => 'privacy_conservation_title',
                'type' => 'text',
                'value' => '6. Durée de conservation',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Utilisation des données',
                'label' => 'Titre durée de conservation',
                'description' => 'Titre de la section sur la durée de conservation des données',
            ],
            [
                'key' => 'privacy_conservation_list',
                'type' => 'text',
                'value' => json_encode([
                    'Données clients : jusqu’à 5 ans maximum après la fin de la relation contractuelle.',
                    'Données de santé : conservées uniquement pour la durée strictement nécessaire au service rendu et traitées avec la plus grande confidentialité.',
                ]),
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Utilisation des données',
                'label' => 'Liste durée de conservation',
                'description' => 'Liste expliquant combien de temps les données sont conservées',
            ],

            // Section Partage des données & Sécurité
            [
                'key' => 'privacy_partage_title',
                'type' => 'text',
                'value' => '7. Partage des données & Sécurité',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Partage des données',
                'label' => 'Titre partage des données',
                'description' => 'Titre de la section sur le partage et la sécurité des données',
            ],
            [
                'key' => 'privacy_partage_intro',
                'type' => 'text',
                'value' => 'Vos données personnelles peuvent être transmises aux entités suivantes, dans la limite de ce qui est strictement nécessaire pour nos services :',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Partage des données',
                'label' => 'Texte introduction partage',
                'description' => 'Introduction du paragraphe expliquant le partage des données',
            ],
            [
                'key' => 'privacy_partage_list',
                'type' => 'text',
                'value' => json_encode([
                    'Nos partenaires de santé (pharmacies) pour la prise en charge d’ordonnances.',
                    'Nos transporteurs pour assurer la livraison.',
                    'Les autorités compétentes en cas d’obligation légale.',
                ]),
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Partage des données',
                'label' => 'Liste partage des données',
                'description' => 'Liste des entités susceptibles de recevoir les données collectées',
            ],
            [
                'key' => 'privacy_partage_footer',
                'type' => 'text',
                'value' => 'Aucune donnée n’est vendue ni transmise à des tiers à des fins commerciales.',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Partage des données',
                'label' => 'Texte conclusion partage',
                'description' => 'Texte de conclusion précisant l’absence de vente des données',
            ],

            // Section Droits des utilisateurs
            [
                'key' => 'privacy_droits_title',
                'type' => 'text',
                'value' => '8. Vos droits (RGPD)',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Droits des utilisateurs',
                'label' => 'Titre droits utilisateurs',
                'description' => 'Titre de la section expliquant les droits des utilisateurs RGPD',
            ],
            [
                'key' => 'privacy_droits_text',
                'type' => 'text',
                'value' => "Conformément au RGPD, vous disposez notamment du Droit d’accès, de Rectification et d’Effacement (droit à l’oubli).",
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Droits des utilisateurs',
                'label' => 'Texte droits RGPD',
                'description' => 'Texte expliquant les droits RGPD des utilisateurs',
            ],
            [
                'key' => 'privacy_droits_email',
                'type' => 'text',
                'value' => 'noha.transports@hotmail.com',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Droits des utilisateurs',
                'label' => 'Email RGPD',
                'description' => 'Adresse email pour exercer les droits RGPD',
            ],

            // Section Cookies
            [
                'key' => 'privacy_cookies_title',
                'type' => 'text',
                'value' => '9. Cookies',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Titre cookies',
                'description' => 'Titre de la section sur l’utilisation des cookies',
            ],
            [
                'key' => 'privacy_cookies_text',
                'type' => 'text',
                'value' => 'Notre site utilise des cookies pour améliorer l’expérience utilisateur et analyser la navigation.',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Texte cookies',
                'description' => 'Texte expliquant l’utilisation des cookies sur le site',
            ],
            [
                'key' => 'privacy_cookies_gestion',
                'type' => 'text',
                'value' => 'Vous pouvez gérer vos préférences directement dans les paramètres de votre navigateur.',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Texte gestion cookies',
                'description' => 'Texte indiquant comment gérer les préférences de cookies',
            ],

            // Section Sécurité et Contact
            [
                'key' => 'privacy_securite_title',
                'type' => 'text',
                'value' => '10. Sécurité et Contact',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Titre sécurité et contact',
                'description' => 'Titre de la section sur la sécurité et le contact',
            ],
            [
                'key' => 'privacy_securite_text',
                'type' => 'text',
                'value' => 'Nous mettons en œuvre des mesures techniques et organisationnelles strictes pour protéger vos données personnelles contre tout accès, utilisation ou divulgation non autorisée.',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Texte sécurité',
                'description' => 'Texte expliquant les mesures de sécurité appliquées',
            ],
            [
                'key' => 'privacy_modification_text',
                'type' => 'text',
                'value' => 'Nous nous réservons le droit de modifier la présente politique à tout moment. La version mise à jour sera publiée sur notre site avec mention de la date de mise à jour.',
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Texte modification politique',
                'description' => 'Texte indiquant la possibilité de mise à jour de la politique',
            ],
            [
                'key' => 'privacy_contact_text',
                'type' => 'text',
                'value' => "Pour toute question, veuillez nous écrire à : noha.transports@hotmail.com \n12 Rue des Arts et Métiers, Immeubles Équinoxes, 97200 Fort-de-France",
                'category' => 'Page',
                'page' => 'Politique de confidentialité',
                'section' => 'Sécurité des données',
                'label' => 'Texte contact',
                'description' => 'Texte donnant les coordonnées de contact pour la confidentialité',
            ],

            // ========================================
            // CONDITIONS D'UTILISATION (legal/terms.blade.php)
            // ========================================
            [
                'key' => 'terms_hero_title',
                'type' => 'text',
                'value' => 'Conditions Générales d\'Utilisation',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Hero',
                'label' => 'Titre principal CGU',
                'description' => 'Titre principal de la page Conditions Générales d’Utilisation',
            ],
            // Section Objet des CGU
            [
                'key' => 'cgu_objet_title',
                'type' => 'text',
                'value' => '1. Objet des CGU',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Acceptation des conditions',
                'label' => 'Titre objet des CGU',
                'description' => 'Titre de la section définissant l’objet des conditions d’utilisation',
            ],
            [
                'key' => 'cgu_objet_paragraph1',
                'type' => 'text',
                'value' => "Les présentes Conditions Générales d’Utilisation (CGU) définissent les modalités d’accès et d’utilisation du site internet et des services proposés par Noha Transports, intermédiaire entre les professionnels de santé et les citoyens pour la prise en charge d’ordonnances et la livraison de médicaments à domicile.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Acceptation des conditions',
                'label' => 'Paragraphe 1 objet',
                'description' => 'Texte principal expliquant l’objet des CGU',
            ],
            [
                'key' => 'cgu_objet_paragraph2',
                'type' => 'text',
                'value' => "En accédant au site et en utilisant nos services, l’utilisateur reconnaît avoir pris connaissance et s’engage à respecter les présentes CGU.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Acceptation des conditions',
                'label' => 'Paragraphe 2 engagement utilisateur',
                'description' => 'Texte stipulant l’acceptation implicite des CGU par l’utilisateur',
            ],

            // Section Services Proposés et Cibles
            [
                'key' => 'cgu_services_title',
                'type' => 'text',
                'value' => '2. Services proposés et cibles',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Titre services proposés',
                'description' => 'Titre de la section présentant les services proposés',
            ],
            [
                'key' => 'cgu_services_intro',
                'type' => 'text',
                'value' => "L’entreprise met à disposition des utilisateurs les services suivants :",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Texte introduction services',
                'description' => 'Introduction présentant la liste des services proposés',
            ],
            [
                'key' => 'cgu_services_list',
                'type' => 'text',
                'value' => json_encode([
                    "Un service de prise en charge de commandes auprès de pharmacies partenaires.",
                    "Un service de livraison de médicaments à domicile (délai indicatif de 24h).",
                ]),
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Liste des services',
                'description' => 'Liste des services fournis par l’entreprise Noha Transports',
            ],
            [
                'key' => 'cgu_services_conclusion',
                'type' => 'text',
                'value' => "Ces services sont principalement destinés aux pharmacies, aidants et citoyens.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Texte conclusion services',
                'description' => 'Texte concluant la section des services proposés et des cibles',
            ],

            // Section Accès au site
            [
                'key' => 'cgu_acces_title',
                'type' => 'text',
                'value' => '3. Accès au site',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Titre accès au site',
                'description' => 'Titre de la section définissant les modalités d’accès au site',
            ],
            [
                'key' => 'cgu_acces_text',
                'type' => 'text',
                'value' => "L’accès au site est libre et gratuit pour tout utilisateur disposant d’un accès internet. Tous les frais liés à la connexion (matériel, logiciel, abonnement, etc.) restent à la charge de l’utilisateur.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Texte accès au site',
                'description' => 'Texte expliquant les conditions d’accès au site internet',
            ],

            // Section Responsabilités de l’utilisateur
            [
                'key' => 'cgu_responsibilite_utilisateur_title',
                'type' => 'text',
                'value' => "4. Responsabilités de l’utilisateur",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Titre responsabilité utilisateur',
                'description' => 'Titre de la section sur les responsabilités de l’utilisateur',
            ],
            [
                'key' => 'cgu_responsibilite_utilisateur_intro',
                'type' => 'text',
                'value' => "L'utilisateur s'engage notamment à :",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Texte introduction responsabilités utilisateur',
                'description' => 'Introduction des engagements de l’utilisateur',
            ],
            [
                'key' => 'cgu_responsibilite_utilisateur_list',
                'type' => 'text',
                'value' => json_encode([
                    "Fournir des informations exactes lors des commandes.",
                    "Respecter la réglementation applicable aux médicaments.",
                    "Ne pas utiliser le site à des fins frauduleuses ou illégales.",
                ]),
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Liste responsabilités utilisateur',
                'description' => 'Liste des obligations et responsabilités de l’utilisateur',
            ],

            // Section Responsabilités de l’entreprise
            [
                'key' => 'cgu_responsabilite_entreprise_title',
                'type' => 'text',
                'value' => '5. Responsabilités de Noha Transports',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Titre responsabilité entreprise',
                'description' => 'Titre de la section sur les engagements de Noha Transports',
            ],
            [
                'key' => 'cgu_responsabilite_entreprise_commitments',
                'type' => 'text',
                'value' => json_encode([
                    "Assurer la livraison des médicaments dans les délais annoncés (24h indicatives).",
                    "Garantir la sécurité et la confidentialité des données (cf. Politique de confidentialité).",
                    "Respecter nos valeurs de prise en charge durable des personnes en perte d’autonomie.",
                ]),
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Liste engagements entreprise',
                'description' => 'Liste des engagements de l’entreprise envers les utilisateurs',
            ],
            [
                'key' => 'cgu_responsabilite_entreprise_limitations',
                'type' => 'text',
                'value' => json_encode([
                    "Des retards ou impossibilités de livraison liés à un cas de force majeure.",
                    "D’un usage non conforme des médicaments par le bénéficiaire.",
                    "De l’indisponibilité temporaire du site (maintenance ou panne technique).",
                ]),
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Liste limitations responsabilité',
                'description' => 'Liste des exclusions de responsabilité de l’entreprise',
            ],

            // Section Commandes et livraisons
            [
                'key' => 'cgu_commandes_title',
                'type' => 'text',
                'value' => '6. Commandes et livraisons',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Titre commandes et livraisons',
                'description' => 'Titre de la section sur la gestion des commandes et livraisons',
            ],
            [
                'key' => 'cgu_commandes_text',
                'type' => 'text',
                'value' => "Les commandes sont gérées exclusivement via le site internet auprès de nos pharmacies partenaires. Le délai de livraison de 24 heures est indicatif et sans garantie contractuelle.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Utilisation du site',
                'label' => 'Texte commandes et livraisons',
                'description' => 'Texte expliquant les modalités de commande et livraison',
            ],

            // Section Données personnelles
            [
                'key' => 'cgu_donnees_title',
                'type' => 'text',
                'value' => '7. Données personnelles',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Titre données personnelles',
                'description' => 'Titre de la section sur le traitement des données personnelles',
            ],
            [
                'key' => 'cgu_donnees_text',
                'type' => 'text',
                'value' => "Dans le cadre de l’utilisation des services, des données personnelles sont collectées et traitées. Veuillez consulter notre Politique de Confidentialité pour les détails sur la collecte et le traitement de vos données.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Responsabilité',
                'label' => 'Texte données personnelles',
                'description' => 'Texte expliquant le lien avec la Politique de Confidentialité',
            ],

            // Section Propriété intellectuelle et dispositions finales
            [
                'key' => 'cgu_propriete_title',
                'type' => 'text',
                'value' => '8. Propriété Intellectuelle & Dispositions Finales',
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Propriété intellectuelle',
                'label' => 'Titre propriété intellectuelle',
                'description' => 'Titre de la section sur la propriété intellectuelle et les dispositions finales',
            ],
            [
                'key' => 'cgu_propriete_intellectuelle',
                'type' => 'text',
                'value' => "Le site, son contenu, sa structure, ainsi que les marques et logos sont la propriété exclusive de l'entreprise. Toute reproduction non autorisée est strictement interdite.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Propriété intellectuelle',
                'label' => 'Texte propriété intellectuelle',
                'description' => 'Texte expliquant les droits de propriété sur le contenu du site',
            ],
            [
                'key' => 'cgu_propriete_modification',
                'type' => 'text',
                'value' => "L’entreprise se réserve le droit de modifier les présentes CGU à tout moment. Les utilisateurs seront informés de ces modifications via le site internet.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Modifications des conditions',
                'label' => 'Texte modification CGU',
                'description' => 'Texte décrivant la procédure de modification des CGU',
            ],
            [
                'key' => 'cgu_propriete_droit',
                'type' => 'text',
                'value' => "Les présentes CGU sont régies par le droit français. En cas de litige, compétence exclusive est attribuée aux tribunaux compétents du ressort du siège social de l’entreprise.",
                'category' => 'Page',
                'page' => 'Conditions Générales d\'Utilisation',
                'section' => 'Modifications des conditions',
                'label' => 'Texte droit applicable',
                'description' => 'Texte de clôture précisant le droit applicable aux CGU',
            ],

        ];

        foreach ($contents as $content) {
            Content::updateOrCreate(['key' => $content['key']], $content);
        }
    }
}
